### ISSUE TITLE
unable to load materials from: model_normalized.mtl

### ISSUE THREAD

**Issue by kxk20001995** [cangumeli/ROCA#14]
Hello, your project is fantastic. It was very helpful to me, but, when I run "python demo.py", the following issues occurred during the operation process:

unable to load materials from: model_normalized.mtl
specified material (material_52_24)  not loaded!
specified material (material_37_24)  not loaded!
specified material (material_27_24)  not loaded!
specified material (material_47_24)  not loaded!
specified material (material_26_24)  not loaded!
specified material (material_24_24)  not loaded!
specified material (material_15_24)  not loaded!
specified material (material_6_24)  not loaded!
specified material (material_1_24)  not loaded!

**Comment by cangumeli** [comment]
We do not use materials (only geometry), so it should not be an issue. You can suppress Trimesh warnings if you wish, e.g., as in [here](https://github.com/mikedh/trimesh/issues/963).
