### ISSUE TITLE
A minor error in README

### ISSUE THREAD

**Issue by C-H-Chien** [cangumeli/ROCA#2]
Hi! I tried the demo by following the instructions in README and it works successfully, except that command should be
```
$ python demo.py --model_path $MODEL_DIR/model_best.pth --data_dir $DATA_DIR/Dataset --config_path $MODEL_DIR/config.yaml
```
where `--model_dir` is changed to `--model_path` and `--config_dir` is changed to `--config_path`.

Please correct me if I am wrong. Thanks!

**Comment by cangumeli** [comment]
Fixed, thanks a lot!
