### ISSUE TITLE
Ask about the positive and negative exemple mining : )

### ISSUE THREAD

**Issue by DoctorXK** [cangumeli/ROCA#4]
Hi dear author,

Thanks for your wonderful job and making the source code public so quickly. I think the idea in the paper of learning a joint embedding between depth object and cad model is clever and easy to understand. But it seems that you are not explaining in paper how to find postive and negative exemples in joint embedding learning. I would be appreciate if you can explain more details about it.

Thanks a lot : )

**Comment by cangumeli** [comment]
Thanks a lot for your interest, we are glad you enjoyed our paper.

We just sample negative and positive CAD models randomly. A hard negative mining strategy may improve the accuracy further if you try that, but we did not pursue this direction in our paper :).

**Comment by DoctorXK** [comment]
Hi there,

I am not quite catch the meaning of "randomly" haha. How do you decide which exemple is positve and which exemple is negative?

**Comment by cangumeli** [comment]
Well based on the Scan2CAD data, we know the ground-truth CAD model for every object instance. The ground-truth CAD model is positive and all the other CAD models from the same category are negative.

**Comment by DoctorXK** [comment]
OK I got it, thank you :）
