### ISSUE TITLE
i can't import something

### ISSUE THREAD

**Issue by WangHaoyuuu** [cangumeli/ROCA#5]
in file predictor.py :
i can't import these as follows:
from roca.config import roca_config
from roca.data import CADCatalog
from roca.data.constants import CAD_TAXONOMY, COLOR_BY_CLASS
from roca.data.datasets import register_scan2cad
from roca.structures import Intrinsics
from roca.utils.alignment_errors import translation_diff
from roca.utils.linalg import make_M_from_tqs
the errors say: Unresolved reference "roca"
it 's a basic issues  however, i can't solve .

**Comment by cangumeli** [comment]
Make sure your working directory is the `network` directory, and you try to run some of the files in that directory (e.g., `demo.py). Do not try to run `predictor.py` file directly as it is inside a package and should not be used as a script.

**Comment by WangHaoyuuu** [comment]
thank you !!!
